    dlina = input("Введите длинну квадрата: \n")
    radius = input("Введите радиус круга: \n")
    visota = input("Введите высоту треугольника: \n")
    print(dlina ** 2 + " - Площадь квадрата.")
    print(dlina * visota // 2 + " - Площадь треугольника.")
    print(radius * 3.14 + " - Площадь круга.")
